name: wealthwhiz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  iconly: ^1.0.1
  intl: ^0.18.1
  lottie: ^2.4.0
  shared_preferences: ^2.1.2
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_charts: ^21.2.10

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - images/